### ISSUE TITLE
`Cannot convert undefined or null to object` in `setDefaultSitemapOptions`

### ISSUE THREAD

**Issue by dargmuesli** [d3xter-dev/sitemap-module-nuxt-3#2] opened 2022-07-06 01:33 UTC
I receive the following error:
```
 FATAL  Cannot convert undefined or null to object                                                                                                                        03:27:38

  at Function.keys (<anonymous>)
  at setDefaultSitemapOptions (node_modules/@funken-studio/sitemap-nuxt-3/dist/module.mjs:196:28)
  at registerSitemap (node_modules/@funken-studio/sitemap-nuxt-3/dist/module.mjs:337:13)
  at registerSitemaps (node_modules/@funken-studio/sitemap-nuxt-3/dist/module.mjs:333:5)
  at node_modules/@funken-studio/sitemap-nuxt-3/dist/module.mjs:413:7
```
It's source is: https://github.com/funken-studio/sitemap-module-nuxt-3/blob/30418ff94f236e22a6b2f2915814350d2753cb05/src/options.ts#L44

**Comment by d3xter-dev** [comment] 2022-07-06 09:09
@dargmuesli I released a new version, should be fixed :)  (added test cases & support for nuxtjs/i18n-edge)  
Please let me know if something seems not to be working as intended!

**Comment by dargmuesli** [comment] 2022-07-06 12:50
Thank you for the quick fix! I now get a different error: `Cannot read properties of undefined (reading 'push')`

Coming from: https://github.com/nuxt/framework/blob/ccec0a37389a5245cbcea98b74c640fd8870cd78/packages/kit/src/server.ts#L39
and: https://github.com/funken-studio/sitemap-module-nuxt-3/blob/91f515cb3c4e880755c34d7b2432dafeb7ada3e3/src/middleware.ts#L59

**Comment by dargmuesli** [comment] 2022-07-06 12:53
For context: I do not use dynamic routes. Thus I did not any of the files mentioned in the README. I only want to have the static paths generated, currently.

**Comment by d3xter-dev** [comment] 2022-07-06 13:06
Could you please provide your  `nuxt.config.ts`?

**Comment by dargmuesli** [comment] 2022-07-06 14:06
Here you go: https://github.com/dargmuesli/jonas-thelemann/blob/master/nuxt.config.ts

**Comment by dargmuesli** [comment] 2022-07-06 14:43
Somehow `nuxtjs/i18n-edge` required single quotation marks around my translation source blocks. This errors:
```
<i18n lang="yml">
de:
  foo: bar
```
this does not:
```
<i18n lang="yml">
de:
  foo: 'bar'
```
Am I missing a migration? Do you know of any @d3xter-dev?

**Comment by d3xter-dev** [comment] 2022-07-06 15:08
`nuxtjs/i18n-edge` is still WIP  so the current documentation might not be correct anymore.  
 I am currently not using i18n in any of my projects, so I can't give you any advanced tips regarding  `nuxtjs/i18n` ^^"
Did that solve your issue though?  If not, then I'll try to find a solution later this evening

**Comment by dargmuesli** [comment] 2022-07-06 15:33
Ok! Not changing `nuxtjs/i18n` it gives now the following to me:

```
ctx.generateTypeDeclarations is not a function                                                      17:30:42

  at Object.getContents (node_modules/@nuxt/bridge/dist/chunks/module.mjs:1076:63)
  at compileTemplate (node_modules/@nuxt/kit/dist/index.mjs:518:21)
  at node_modules/@nuxt/kit/dist/index.mjs:622:30
  at async Nuxt.callHook (node_modules/hable/dist/hable.js:1:959)
  at async Builder.compileTemplates (node_modules/@nuxt/builder-edge/dist/builder.js:505:5)
  at async Builder.generateRoutesAndFiles (node_modules/@nuxt/builder-edge/dist/builder.js:298:5)
  at async Builder.build (node_modules/@nuxt/builder-edge/dist/builder.js:259:5)
```

I don't see your module in the stack trace. I must say, that I'm trying all of that with fix https://github.com/nuxt/bridge/pull/324 already applied.

**Closed as completed** 2022-11-18 21:16 UTC

**Comment by dargmuesli** [comment] 2022-11-22 11:01
Thank you @d3xter-dev, it works fine now!
